### ISSUE TITLE
what dependencies are needed?

### ISSUE THREAD

**Issue by tayvenb13** [cloudant-labs/easton#4]
I am trying to build hastings/easton into couchdb 2.0 for geospatial indexing. When trying to run the `./configure --disable-fauxton --disable-docs && make release ` I end up with missing files for Easton such as 
`==> easton (compile)
Compiling /couchdb/apache-couchdb-2.0.0/src/easton/c_src/easton_index/command.cc
In file included from c_src/easton_index/index.hh:21:0,
                 from c_src/easton_index/command.hh:17,
                 from /couchdb/apache-couchdb-2.0.0/src/easton/c_src/easton_index/command.cc:16:
c_src/easton_index/geo.hh:21:20: fatal error: geos_c.h: No such file or directory
compilation terminated.
ERROR: compile failed while processing /couchdb/apache-couchdb-2.0.0/src/easton: rebar_abort
Makefile:67: recipe for target 'couch' failed
make: *** [couch] Error 1`
or
`==> easton (compile)
Compiling /couchdb/apache-couchdb-2.0.0/src/easton/c_src/easton_index/geo.cc
/couchdb/apache-couchdb-2.0.0/src/easton/c_src/easton_index/geo.cc:28:26: fatal error: CsMap/cs_map.h: No such file or directory
compilation terminated.`

What dependencies am I missing?

**Comment by nickva** [comment]
@furrycoat21 

Try these:

_libspatialindex_: https://github.com/cloudant/libspatialindex

_geos 3.5.1_ : http://download.osgeo.org/geos/geos-3.5.1.tar.bz2

_csmap 14.01_: https://svn.osgeo.org/metacrs/csmap/branches/14.01/ 
This an svn repo, couldn't find a download. And this is kinda of a pain to install. Follow instructions info on how to get the source here: https://trac.osgeo.org/csmap/wiki/HowToGetTheSourceCode. There is a GH fork as well. Maybe that's easier to install: https://github.com/normanb/CS-Map it also contains build instructions.

_leveldb_ (I used 1.20): https://github.com/google/leveldb

**Comment by tayvenb13** [comment]
Hey @nickva 

Those worked great! Just some notes on what I found. 

csmap was a pain to install and had to be installed with version 14.01. To install it follow the instructions in https://svn.osgeo.org/metacrs/csmap/branches/14.01/CsMapDev/ReadMe.txt then copy the Include dir to /usr/local/Include/CsMap and ~/CsMapDev/Source/CsMap.a to /usr/local/lib/CsMap.a 
The github repo didn't work for me. 

geos was only supported at 3.5.1, rather than the newer 3.6.1. 

leveldb worked using the most recent version for me.

**Comment by tropperstyle** [comment]
Also adding to @furrycoat21 on csmap I needed to also `cp -r CsMapDev/Dictionaries/* /usr/share/CsMap/dict` to get radius queries working.
